### ISSUE TITLE
Party seats seem inaccurate

### ISSUE THREAD

**Issue by rauhanisti** [polettif/proporz#2]
I feel like there is something off with the party divisors:

The seats allocated to each party differ more than they should from their share of votes. Please see attached the data I used.
[votes_FIN_2019.xlsx](https://github.com/polettif/proporz/files/4971611/votes_FIN_2019.xlsx)
[district_seats_FIN_2019.xlsx](https://github.com/polettif/proporz/files/4971612/district_seats_FIN_2019.xlsx)

Using a 0.5 % national treshold, e.g. party "RKP" should land 9 seats, but using _pukelsheim_ only gives them 7. 
"VAS" should be entitled to 17 due to their share, but they get 18 etc.

The specs I use:
```
seats_df = pukelsheim(votes_df,
                      district_seats_df,
                      quorum_districts = 0,
                      quorum_total = 0.005)
```
Here is how precise results I got by finding the divisors by hand:
[result_Pukelsheim_by_hand_FIN_2019.xlsx](https://github.com/polettif/proporz/files/4971708/result_Pukelsheim_by_hand_FIN_2019.xlsx)

Am I missing something? Thanks for your patience!

**Comment by polettif** [comment]
First of all, thanks for testing the package and bringing up those issues. There was indeed a bug in the quorum calculations (or rather the lack thereof). I fixed that in [this commit](https://github.com/polettif/proporz/commit/533e452a3da7a27059db490c2a2633f2f4cd470d)

> Am I missing something?

I guess so because you can't simply add all votes and divide by the number of seats if you're using biproportional apportionment.

The general assumption for (bi)proportional apportionment is that one person can vote as many times as there are seats in their district. So in your case, a person in HEL can vote 22 times and distribute their votes among lists/parties. However, this means that you cannot simply add all votes for a party across all districts because that way votes in districts with more seats are worth more. Very simple example: Party A gets one voter in HEL and party B gets one voter in LAP. Both parties have one voter (and should thus get the same number of seats nationally) but Party A got 22 _list votes_ whereas party B got 7 _list votes_. This means we need to weigh votes per district which happens in `upper_apportionment`. Unfortunately, the example given in [the English Wikipedia article](https://en.wikipedia.org/wiki/Biproportional_apportionment) assumes that the number of seats _per district_ is depending on the number of votes. Usually though (and how it's implemented in `pukelsheim`) the number of seats per district is calculated based on population and already known before the election. 

The following, rather extreme, example illustrates the calcuations:

|                 | raw list votes |            |   | weighted votes |            |           |
|-----------------|----------------|------------|---|----------------|------------|-----------|
|                 | District 1     | District 2 |   | District 1     | District 2 |           |
| Party A         | 50             | 1          |   | 5              | 1          | 6 (46.2%) |
| Party B         | 20             | 5          |   | 2              | 5          | 7 (53.8%) |
|                 |                |            |   |                |            |           |
| District Seats: | 10             | 1          |   |                |            |           |

Party A got 51 list votes (out of 76, so 66%). However, if we weigh those votes by district size, only 6 people have voted for party A nationally. Party B was very strong in district 2 and got more weighted votes (or "voters") nationally, 7 voters or 54%. The `pukelsheim` algorithm uses 46 and 54% percent as party vote shares.

I [did expand `biproportional`](https://github.com/polettif/proporz/commit/9b47e367712b4e1ef22440a2bd2c840f042318ec) to allow free district seat numbers as well but If the number of seats per district is given (as in your use case), the votes are always weighted.

**Comment by rauhanisti** [comment]
Thank you for your explanation! I think I am getting there :)

> The general assumption for (bi)proportional apportionment is that one person can vote as many times as there are seats in their district. So in your case, a person in HEL can vote 22 times and distribute their votes among lists/parties.

This would be an ideal system indeed, but the Finnish data only includes 1 vote / voter. Should I actually multiply all district votes by the number of seats assigned in that district? Seats/district are constant in Finland as well, as they are based on population and decided before the elections.

**Comment by polettif** [comment]
> This would be an ideal system indeed, but the Finnish data only includes 1 vote / voter. 

Ah I see! I'll update the documentation accordingly. A parameter like `list_votes=FALSE` or something like that might be useful.

> Should I actually multiply all district votes by the number of seats assigned in that district?

Yes that's the way to go for now.

**Comment by polettif** [comment]
Some housekeeping:
- use_list_votes was added in [3f01eab](https://github.com/polettif/proporz/commit/3f01eab5bc930f8a759274dfb70d063c6092834d)
- the full Finnish data set is now available in proporz
